# dbt project - Lakehouse TASY
# Orquestrado via Airflow Cosmos
name: "lakehouse_tasy"
version: "1.0.0"
config-version: 2
profile: "lakehouse_tasy"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # CDC Bronze
  cdc_lookback_hours: 2
  cdc_reprocess_hours: 0

  # dim_tempo — range do calendário global
  # Para expandir: atualizar dim_tempo_end_date e executar `dbt build --select dim_tempo`
  dim_tempo_start_date: '2010-01-01'
  dim_tempo_end_date:   '2030-01-01'


models:
  lakehouse_tasy:
    bronze:
      +schema: bronze
      +materialized: table
      +file_format: iceberg
    silver:
      +schema: silver
      +file_format: iceberg
      +materialized: table
    silver_context:
      +schema: silver_context
      +file_format: iceberg
      +materialized: table
    gold:
      +schema: gold
      +file_format: iceberg
      +materialized: table
