# dbt-spark profiles - Spark Thrift
# Variáveis: SPARK_THRIFT_HOST, SPARK_THRIFT_USER, SPARK_THRIFT_PASSWORD
lakehouse_tasy:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      auth: LDAP
      schema: raw
      host: "{{ env_var('SPARK_THRIFT_HOST') }}"
      port: 10000
      user: "{{ env_var('SPARK_THRIFT_USER') }}"
      password: "{{ env_var('SPARK_THRIFT_PASSWORD') }}"
      connect_timeout: 60
      connect_retries: 3
      retry_all: true
      server_side_parameters:
        "spark.sql.catalog.spark_catalog": "org.apache.iceberg.spark.SparkSessionCatalog"
        "spark.sql.catalog.spark_catalog.type": "hive"
        "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
