{#- Silver: one column per line + macros (dbt/macros/). PK: nr_sequencia. -#}
{{
  config(
    materialized='incremental',
    schema='silver',
    unique_key='nr_sequencia',
    incremental_strategy='merge',
    merge_update_columns=[
      'nr_atendimento', 'dt_entrada_unidade', 'cd_procedimento', 'dt_procedimento',
      'qt_procedimento', 'dt_atualizacao', 'nm_usuario', 'cd_medico', 'cd_convenio',
      'cd_categoria', 'cd_pessoa_fisica', 'dt_prescricao', 'ds_observacao', 'vl_procedimento',
      'vl_medico', 'vl_anestesista', 'vl_materiais', 'cd_edicao_amb', 'cd_tabela_servico',
      'dt_vigencia_preco', 'cd_procedimento_princ', 'dt_procedimento_princ', 'dt_acerto_conta',
      'dt_acerto_convenio', 'dt_acerto_medico', 'vl_auxiliares', 'vl_custo_operacional',
      'tx_medico', 'tx_anestesia', 'nr_prescricao', 'nr_sequencia_prescricao',
      'cd_motivo_exc_conta', 'ds_compl_motivo_excon', 'cd_acao', 'qt_devolvida',
      'cd_motivo_devolucao', 'nr_cirurgia', 'nr_doc_convenio', 'cd_medico_executor',
      'ie_cobra_pf_pj', 'nr_laudo', 'dt_conta', 'cd_setor_atendimento', 'cd_conta_contabil',
      'cd_procedimento_aih', 'ie_origem_proced', 'nr_aih', 'ie_responsavel_credito',
      'tx_procedimento', 'cd_equipamento', 'ie_valor_informado', 'cd_estabelecimento_custo',
      'cd_tabela_custo', 'cd_situacao_glosa', 'nr_lote_contabil', 'cd_procedimento_convenio',
      'nr_seq_autorizacao', 'ie_tipo_servico_sus', 'ie_tipo_ato_sus', 'cd_cgc_prestador',
      'nr_nf_prestador', 'cd_atividade_prof_bpa', 'nr_interno_conta', 'nr_seq_proc_princ',
      'ie_guia_informada', 'dt_inicio_procedimento', 'ie_emite_conta', 'ie_funcao_medico',
      'ie_classif_sus', 'cd_especialidade', 'nm_usuario_original', 'nr_seq_proc_pacote',
      'ie_tipo_proc_sus', 'cd_setor_receita', 'vl_adic_plant', 'qt_porte_anestesico',
      'tx_hora_extra', 'ie_emite_conta_honor', 'nr_seq_atepacu', 'ie_proc_princ_atend',
      'cd_medico_req', 'ie_tipo_guia', 'ie_video', 'nr_doc_interno', 'ie_auditoria',
      'nr_seq_grupo_rec', 'cd_medico_convenio', 'cd_motivo_ajuste', 'ie_via_acesso',
      'nr_seq_cor_exec', 'nr_seq_exame', 'ie_intercorrencia', 'nr_seq_origem', 'ie_dispersao',
      'cd_setor_paciente', 'nr_seq_conta_origem', 'nr_seq_parcial', 'nr_seq_proc_interno',
      'cd_senha', 'nr_seq_aih', 'nr_doc_honor_conv', 'dt_conferencia', 'ie_tipo_atend_bpa',
      'ie_grupo_atend_bpa', 'cd_cgc_prestador_conta', 'cd_medico_exec_conta', 'nr_seq_pq_proc',
      'qt_filme', 'nr_seq_proc_crit_repasse', 'cd_senha_autor', 'cd_autor_convenio',
      'nr_seq_regra_lanc', 'ie_tiss_tipo_guia', 'nr_seq_tiss_tabela', 'nr_minuto_duracao',
      'ie_tiss_tipo_guia_honor', 'nr_seq_regra_preco', 'ie_tiss_tipo_guia_desp',
      'ie_tecnica_utilizada', 'ie_tiss_tipo_despesa', 'cd_cgc_prestador_tiss',
      'cd_cgc_honorario_tiss', 'ie_integracao', 'nr_seq_proc_acerto', 'vl_original_tabela',
      'cd_doenca_cid', 'nr_seq_apac', 'nr_seq_ajuste_proc', 'cd_tab_custo_preco',
      'nr_seq_proc_autor', 'ie_doc_executor', 'nr_seq_regra_doc', 'cd_cbo', 'cd_prestador_tiss',
      'cd_cgc_prest_solic_tiss', 'cd_setor_resp', 'dt_final_procedimento', 'ie_tiss_desp_honor',
      'nr_seq_proc_est', 'cd_prest_resp', 'cd_medico_exec_tiss', 'ds_proc_tiss',
      'nr_seq_tamanho_filme', 'ds_prestador_tiss', 'nr_seq_proc_crit_hor', 'nr_seq_reg_template',
      'cd_procedimento_tuss', 'ie_ratear_item', 'ie_complexidade', 'ie_tipo_financiamento',
      'cd_funcao', 'cd_perfil', 'nr_seq_regra_qtde_exec', 'cd_centro_custo_receita',
      'nr_seq_regra_guia_tiss', 'nr_seq_regra_honor_tiss', 'ie_tipo_atend_tiss', 'vl_desp_tiss',
      'ie_resp_cred_manual', 'nr_seq_just_valor_inf', 'cd_medico_solic_tiss',
      'cd_medico_prof_solic_tiss', 'vl_repasse_calc', 'tx_custo_oper_qt', 'ie_spect',
      'nr_seq_agenda_rxt', 'cd_prestador_solic_tiss', 'ds_prestador_solic_tiss', 'vl_tx_desconto',
      'vl_tx_adm', 'cd_medico_honor_tiss', 'nr_controle', 'nr_seq_regra_taxa_cir',
      'nr_seq_proc_orig', 'nr_sequencia_gas', 'nr_seq_etapa_checkup', 'nr_seq_checkup_etapa',
      'ie_via_hemodinamica', 'cd_regra_repasse', 'ie_trat_conta_rn', 'nr_seq_reg_proced',
      'nr_seq_pepo', 'nr_seq_motivo_incl', 'dt_conversao_manual', 'cd_cgc_prest_honor_tiss',
      'nr_seq_transfusao', 'nr_seq_reserva', 'ie_lado', 'nr_seq_hc_equipamento',
      'dt_vinc_proced_adic', 'ds_indicacao', 'cd_tipo_anestesia', 'nr_seq_lanc_acao',
      'nr_seq_material', 'ie_carater_cirurgia', 'ds_just_valor_inf', 'nr_fone_integracao',
      'dt_ligacao_integracao', 'ds_just_alter_data', 'cd_medico_prev_laudo', 'nr_seq_orig_audit',
      'nr_seq_servico', 'nr_seq_servico_classif', 'nr_seq_sus_equipe', 'nr_seq_proc_ditado',
      'nr_seq_crit_honorario', 'ie_tx_cir_tempo', 'nr_seq_pe_prescr', 'cd_medico_autenticacao',
      'dt_autenticacao', 'ds_biometria', 'nr_seq_prescr_mat', 'nr_seq_solucao',
      'nr_seq_proc_desdob', 'cd_medico_residente', 'ie_retorno', 'nr_ato_ipasgo',
      'nr_seq_conta_reversao', 'nr_seq_regra_pepo', 'ds_proc_tuss', 'nr_seq_tuss_item',
      'cd_sequencia_parametro', 'tx_auxiliar', 'cd_autorizacao_prest', 'nr_presc_mipres',
      'cd_id_entrega', 'nr_seq_proc_pacote_origem', '_is_deleted', '_cdc_op', '_cdc_event_at',
      '_cdc_ts_ms', '_bronze_row_hash', '_bronze_loaded_at', '_dbt_invocation_id',
    ],
    file_format='iceberg',
    on_schema_change='append_new_columns',
    tags=["silver", "tasy", "procedimento_paciente"],
    post_hook=post_hook_delete_source_tombstones('bronze_tasy_procedimento_paciente', 'nr_sequencia', '_is_deleted')
  )
}}

WITH base AS (
  SELECT * FROM {{ ref('bronze_tasy_procedimento_paciente') }} b
  {% if is_incremental() %}
  WHERE b._bronze_loaded_at > (
      SELECT COALESCE(MAX(s._silver_processed_at), CAST('1900-01-01' AS TIMESTAMP))
      FROM {{ this }} s
  )
  {% endif %}
)
, latest_by_pk AS (
  SELECT *
  FROM (
    SELECT
        b.*
      , ROW_NUMBER() OVER (
          PARTITION BY b.nr_sequencia
          ORDER BY
              CAST(COALESCE(b._cdc_ts_ms, 0) AS BIGINT) DESC
            , CAST(COALESCE(b.__source_txid, 0) AS BIGINT) DESC
        ) AS _rn
    FROM base b
  ) x
  WHERE _rn = 1
)
,
shaped AS (
  SELECT
    d.nr_sequencia AS nr_sequencia,
    {{ fill_null_bigint('d.nr_atendimento', -1) }} AS nr_atendimento,
    {{ standardize_date('d.dh_entrada_unidade') }} AS dt_entrada_unidade,
    {{ fill_null_bigint('d.cd_procedimento', -1) }} AS cd_procedimento,
    {{ standardize_date('d.dh_procedimento') }} AS dt_procedimento,
    {{ normalize_decimal('d.qt_procedimento', 2, -1) }} AS qt_procedimento,
    {{ standardize_date('d.dh_atualizacao') }} AS dt_atualizacao,
    {{ standardize_text_initcap('d.nm_usuario', "'indefinido'") }} AS nm_usuario,
    {{ fill_null_bigint('d.cd_medico', -1) }} AS cd_medico,
    {{ fill_null_bigint('d.cd_convenio', -1) }} AS cd_convenio,
    {{ fill_null_bigint('d.cd_categoria', -1) }} AS cd_categoria,
    {{ fill_null_bigint('d.cd_pessoa_fisica', -1) }} AS cd_pessoa_fisica,
    {{ standardize_date('d.dh_prescricao') }} AS dt_prescricao,
    {{ standardize_text_initcap('d.ds_observacao', "'indefinido'") }} AS ds_observacao,
    {{ normalize_decimal('d.vl_procedimento', 2, -1) }} AS vl_procedimento,
    {{ normalize_decimal('d.vl_medico', 2, -1) }} AS vl_medico,
    {{ normalize_decimal('d.vl_anestesista', 2, -1) }} AS vl_anestesista,
    {{ normalize_decimal('d.vl_materiais', 2, -1) }} AS vl_materiais,
    {{ fill_null_bigint('d.cd_edicao_amb', -1) }} AS cd_edicao_amb,
    {{ fill_null_bigint('d.cd_tabela_servico', -1) }} AS cd_tabela_servico,
    {{ standardize_date('d.dh_vigencia_preco') }} AS dt_vigencia_preco,
    {{ fill_null_bigint('d.cd_procedimento_princ', -1) }} AS cd_procedimento_princ,
    {{ standardize_date('d.dh_procedimento_princ') }} AS dt_procedimento_princ,
    {{ standardize_date('d.dh_acerto_conta') }} AS dt_acerto_conta,
    {{ standardize_date('d.dh_acerto_convenio') }} AS dt_acerto_convenio,
    {{ standardize_date('d.dh_acerto_medico') }} AS dt_acerto_medico,
    {{ normalize_decimal('d.vl_auxiliares', 2, -1) }} AS vl_auxiliares,
    {{ normalize_decimal('d.vl_custo_operacional', 2, -1) }} AS vl_custo_operacional,
    {{ normalize_decimal('d.tx_medico', 2, -1) }} AS tx_medico,
    {{ normalize_decimal('d.tx_anestesia', 2, -1) }} AS tx_anestesia,
    {{ fill_null_bigint('d.nr_prescricao', -1) }} AS nr_prescricao,
    {{ fill_null_bigint('d.nr_sequencia_prescricao', -1) }} AS nr_sequencia_prescricao,
    {{ fill_null_bigint('d.cd_motivo_exc_conta', -1) }} AS cd_motivo_exc_conta,
    {{ standardize_text_initcap('d.ds_compl_motivo_excon', "'indefinido'") }} AS ds_compl_motivo_excon,
    {{ fill_null_bigint('d.cd_acao', -1) }} AS cd_acao,
    {{ normalize_decimal('d.qt_devolvida', 2, -1) }} AS qt_devolvida,
    {{ fill_null_bigint('d.cd_motivo_devolucao', -1) }} AS cd_motivo_devolucao,
    {{ fill_null_bigint('d.nr_cirurgia', -1) }} AS nr_cirurgia,
    {{ fill_null_bigint('d.nr_doc_convenio', -1) }} AS nr_doc_convenio,
    {{ fill_null_bigint('d.cd_medico_executor', -1) }} AS cd_medico_executor,
    {{ standardize_enum('d.ie_cobra_pf_pj', "'i'") }} AS ie_cobra_pf_pj,
    {{ fill_null_bigint('d.nr_laudo', -1) }} AS nr_laudo,
    {{ standardize_date('d.dh_conta') }} AS dt_conta,
    {{ fill_null_bigint('d.cd_setor_atendimento', -1) }} AS cd_setor_atendimento,
    {{ fill_null_bigint('d.cd_conta_contabil', -1) }} AS cd_conta_contabil,
    {{ fill_null_bigint('d.cd_procedimento_aih', -1) }} AS cd_procedimento_aih,
    {{ standardize_enum('d.ie_origem_proced', "'i'") }} AS ie_origem_proced,
    {{ fill_null_bigint('d.nr_aih', -1) }} AS nr_aih,
    {{ standardize_enum('d.ie_responsavel_credito', "'i'") }} AS ie_responsavel_credito,
    {{ normalize_decimal('d.tx_procedimento', 2, -1) }} AS tx_procedimento,
    {{ fill_null_bigint('d.cd_equipamento', -1) }} AS cd_equipamento,
    {{ standardize_enum('d.ie_valor_informado', "'i'") }} AS ie_valor_informado,
    {{ fill_null_bigint('d.cd_estabelecimento_custo', -1) }} AS cd_estabelecimento_custo,
    {{ fill_null_bigint('d.cd_tabela_custo', -1) }} AS cd_tabela_custo,
    {{ fill_null_bigint('d.cd_situacao_glosa', -1) }} AS cd_situacao_glosa,
    {{ fill_null_bigint('d.nr_lote_contabil', -1) }} AS nr_lote_contabil,
    {{ fill_null_bigint('d.cd_procedimento_convenio', -1) }} AS cd_procedimento_convenio,
    {{ fill_null_bigint('d.nr_seq_autorizacao', -1) }} AS nr_seq_autorizacao,
    {{ standardize_enum('d.ie_tipo_servico_sus', "'i'") }} AS ie_tipo_servico_sus,
    {{ standardize_enum('d.ie_tipo_ato_sus', "'i'") }} AS ie_tipo_ato_sus,
    {{ standardize_documents('d.cd_cgc_prestador', 14) }} AS cd_cgc_prestador,
    {{ fill_null_bigint('d.nr_nf_prestador', -1) }} AS nr_nf_prestador,
    {{ fill_null_bigint('d.cd_atividade_prof_bpa', -1) }} AS cd_atividade_prof_bpa,
    {{ fill_null_bigint('d.nr_interno_conta', -1) }} AS nr_interno_conta,
    {{ fill_null_bigint('d.nr_seq_proc_princ', -1) }} AS nr_seq_proc_princ,
    {{ standardize_enum('d.ie_guia_informada', "'i'") }} AS ie_guia_informada,
    {{ standardize_date('d.dh_inicio_procedimento') }} AS dt_inicio_procedimento,
    {{ standardize_enum('d.ie_emite_conta', "'i'") }} AS ie_emite_conta,
    {{ standardize_enum('d.ie_funcao_medico', "'i'") }} AS ie_funcao_medico,
    {{ standardize_enum('d.ie_classif_sus', "'i'") }} AS ie_classif_sus,
    {{ fill_null_bigint('d.cd_especialidade', -1) }} AS cd_especialidade,
    {{ standardize_text_initcap('d.nm_usuario_original', "'indefinido'") }} AS nm_usuario_original,
    {{ fill_null_bigint('d.nr_seq_proc_pacote', -1) }} AS nr_seq_proc_pacote,
    {{ standardize_enum('d.ie_tipo_proc_sus', "'i'") }} AS ie_tipo_proc_sus,
    {{ fill_null_bigint('d.cd_setor_receita', -1) }} AS cd_setor_receita,
    {{ normalize_decimal('d.vl_adic_plant', 2, -1) }} AS vl_adic_plant,
    {{ normalize_decimal('d.qt_porte_anestesico', 2, -1) }} AS qt_porte_anestesico,
    {{ normalize_decimal('d.tx_hora_extra', 2, -1) }} AS tx_hora_extra,
    {{ standardize_enum('d.ie_emite_conta_honor', "'i'") }} AS ie_emite_conta_honor,
    {{ fill_null_bigint('d.nr_seq_atepacu', -1) }} AS nr_seq_atepacu,
    {{ standardize_enum('d.ie_proc_princ_atend', "'i'") }} AS ie_proc_princ_atend,
    {{ fill_null_bigint('d.cd_medico_req', -1) }} AS cd_medico_req,
    {{ standardize_enum('d.ie_tipo_guia', "'i'") }} AS ie_tipo_guia,
    {{ standardize_enum('d.ie_video', "'i'") }} AS ie_video,
    {{ fill_null_bigint('d.nr_doc_interno', -1) }} AS nr_doc_interno,
    {{ standardize_enum('d.ie_auditoria', "'i'") }} AS ie_auditoria,
    {{ fill_null_bigint('d.nr_seq_grupo_rec', -1) }} AS nr_seq_grupo_rec,
    {{ fill_null_bigint('d.cd_medico_convenio', -1) }} AS cd_medico_convenio,
    {{ fill_null_bigint('d.cd_motivo_ajuste', -1) }} AS cd_motivo_ajuste,
    {{ standardize_enum('d.ie_via_acesso', "'i'") }} AS ie_via_acesso,
    {{ fill_null_bigint('d.nr_seq_cor_exec', -1) }} AS nr_seq_cor_exec,
    {{ fill_null_bigint('d.nr_seq_exame', -1) }} AS nr_seq_exame,
    {{ standardize_enum('d.ie_intercorrencia', "'i'") }} AS ie_intercorrencia,
    {{ fill_null_bigint('d.nr_seq_origem', -1) }} AS nr_seq_origem,
    {{ standardize_enum('d.ie_dispersao', "'i'") }} AS ie_dispersao,
    {{ fill_null_bigint('d.cd_setor_paciente', -1) }} AS cd_setor_paciente,
    {{ fill_null_bigint('d.nr_seq_conta_origem', -1) }} AS nr_seq_conta_origem,
    {{ fill_null_bigint('d.nr_seq_parcial', -1) }} AS nr_seq_parcial,
    {{ fill_null_bigint('d.nr_seq_proc_interno', -1) }} AS nr_seq_proc_interno,
    {{ fill_null_bigint('d.cd_senha', -1) }} AS cd_senha,
    {{ fill_null_bigint('d.nr_seq_aih', -1) }} AS nr_seq_aih,
    {{ fill_null_bigint('d.nr_doc_honor_conv', -1) }} AS nr_doc_honor_conv,
    {{ standardize_date('d.dh_conferencia') }} AS dt_conferencia,
    {{ standardize_enum('d.ie_tipo_atend_bpa', "'i'") }} AS ie_tipo_atend_bpa,
    {{ standardize_enum('d.ie_grupo_atend_bpa', "'i'") }} AS ie_grupo_atend_bpa,
    {{ standardize_documents('d.cd_cgc_prestador_conta', 14) }} AS cd_cgc_prestador_conta,
    {{ fill_null_bigint('d.cd_medico_exec_conta', -1) }} AS cd_medico_exec_conta,
    {{ fill_null_bigint('d.nr_seq_pq_proc', -1) }} AS nr_seq_pq_proc,
    {{ normalize_decimal('d.qt_filme', 2, -1) }} AS qt_filme,
    {{ fill_null_bigint('d.nr_seq_proc_crit_repasse', -1) }} AS nr_seq_proc_crit_repasse,
    {{ fill_null_bigint('d.cd_senha_autor', -1) }} AS cd_senha_autor,
    {{ fill_null_bigint('d.cd_autor_convenio', -1) }} AS cd_autor_convenio,
    {{ fill_null_bigint('d.nr_seq_regra_lanc', -1) }} AS nr_seq_regra_lanc,
    {{ standardize_enum('d.ie_tiss_tipo_guia', "'i'") }} AS ie_tiss_tipo_guia,
    {{ fill_null_bigint('d.nr_seq_tiss_tabela', -1) }} AS nr_seq_tiss_tabela,
    {{ fill_null_bigint('d.nr_minuto_duracao', -1) }} AS nr_minuto_duracao,
    {{ standardize_enum('d.ie_tiss_tipo_guia_honor', "'i'") }} AS ie_tiss_tipo_guia_honor,
    {{ fill_null_bigint('d.nr_seq_regra_preco', -1) }} AS nr_seq_regra_preco,
    {{ standardize_enum('d.ie_tiss_tipo_guia_desp', "'i'") }} AS ie_tiss_tipo_guia_desp,
    {{ standardize_enum('d.ie_tecnica_utilizada', "'i'") }} AS ie_tecnica_utilizada,
    {{ standardize_enum('d.ie_tiss_tipo_despesa', "'i'") }} AS ie_tiss_tipo_despesa,
    {{ standardize_documents('d.cd_cgc_prestador_tiss', 14) }} AS cd_cgc_prestador_tiss,
    {{ standardize_documents('d.cd_cgc_honorario_tiss', 14) }} AS cd_cgc_honorario_tiss,
    {{ standardize_enum('d.ie_integracao', "'i'") }} AS ie_integracao,
    {{ fill_null_bigint('d.nr_seq_proc_acerto', -1) }} AS nr_seq_proc_acerto,
    {{ normalize_decimal('d.vl_original_tabela', 2, -1) }} AS vl_original_tabela,
    {{ fill_null_bigint('d.cd_doenca_cid', -1) }} AS cd_doenca_cid,
    {{ fill_null_bigint('d.nr_seq_apac', -1) }} AS nr_seq_apac,
    {{ fill_null_bigint('d.nr_seq_ajuste_proc', -1) }} AS nr_seq_ajuste_proc,
    {{ fill_null_bigint('d.cd_tab_custo_preco', -1) }} AS cd_tab_custo_preco,
    {{ fill_null_bigint('d.nr_seq_proc_autor', -1) }} AS nr_seq_proc_autor,
    {{ standardize_enum('d.ie_doc_executor', "'i'") }} AS ie_doc_executor,
    {{ fill_null_bigint('d.nr_seq_regra_doc', -1) }} AS nr_seq_regra_doc,
    {{ fill_null_bigint('d.cd_cbo', -1) }} AS cd_cbo,
    {{ fill_null_bigint('d.cd_prestador_tiss', -1) }} AS cd_prestador_tiss,
    {{ standardize_documents('d.cd_cgc_prest_solic_tiss', 14) }} AS cd_cgc_prest_solic_tiss,
    {{ fill_null_bigint('d.cd_setor_resp', -1) }} AS cd_setor_resp,
    {{ standardize_date('d.dh_final_procedimento') }} AS dt_final_procedimento,
    {{ standardize_enum('d.ie_tiss_desp_honor', "'i'") }} AS ie_tiss_desp_honor,
    {{ fill_null_bigint('d.nr_seq_proc_est', -1) }} AS nr_seq_proc_est,
    {{ fill_null_bigint('d.cd_prest_resp', -1) }} AS cd_prest_resp,
    {{ fill_null_bigint('d.cd_medico_exec_tiss', -1) }} AS cd_medico_exec_tiss,
    {{ standardize_text_initcap('d.ds_proc_tiss', "'indefinido'") }} AS ds_proc_tiss,
    {{ fill_null_bigint('d.nr_seq_tamanho_filme', -1) }} AS nr_seq_tamanho_filme,
    {{ standardize_text_initcap('d.ds_prestador_tiss', "'indefinido'") }} AS ds_prestador_tiss,
    {{ fill_null_bigint('d.nr_seq_proc_crit_hor', -1) }} AS nr_seq_proc_crit_hor,
    {{ fill_null_bigint('d.nr_seq_reg_template', -1) }} AS nr_seq_reg_template,
    {{ fill_null_bigint('d.cd_procedimento_tuss', -1) }} AS cd_procedimento_tuss,
    {{ standardize_enum('d.ie_ratear_item', "'i'") }} AS ie_ratear_item,
    {{ standardize_enum('d.ie_complexidade', "'i'") }} AS ie_complexidade,
    {{ standardize_enum('d.ie_tipo_financiamento', "'i'") }} AS ie_tipo_financiamento,
    {{ fill_null_bigint('d.cd_funcao', -1) }} AS cd_funcao,
    {{ fill_null_bigint('d.cd_perfil', -1) }} AS cd_perfil,
    {{ fill_null_bigint('d.nr_seq_regra_qtde_exec', -1) }} AS nr_seq_regra_qtde_exec,
    {{ fill_null_bigint('d.cd_centro_custo_receita', -1) }} AS cd_centro_custo_receita,
    {{ fill_null_bigint('d.nr_seq_regra_guia_tiss', -1) }} AS nr_seq_regra_guia_tiss,
    {{ fill_null_bigint('d.nr_seq_regra_honor_tiss', -1) }} AS nr_seq_regra_honor_tiss,
    {{ standardize_enum('d.ie_tipo_atend_tiss', "'i'") }} AS ie_tipo_atend_tiss,
    {{ normalize_decimal('d.vl_desp_tiss', 2, -1) }} AS vl_desp_tiss,
    {{ standardize_enum('d.ie_resp_cred_manual', "'i'") }} AS ie_resp_cred_manual,
    {{ fill_null_bigint('d.nr_seq_just_valor_inf', -1) }} AS nr_seq_just_valor_inf,
    {{ fill_null_bigint('d.cd_medico_solic_tiss', -1) }} AS cd_medico_solic_tiss,
    {{ fill_null_bigint('d.cd_medico_prof_solic_tiss', -1) }} AS cd_medico_prof_solic_tiss,
    {{ normalize_decimal('d.vl_repasse_calc', 2, -1) }} AS vl_repasse_calc,
    {{ normalize_decimal('d.tx_custo_oper_qt', 2, -1) }} AS tx_custo_oper_qt,
    {{ standardize_enum('d.ie_spect', "'i'") }} AS ie_spect,
    {{ fill_null_bigint('d.nr_seq_agenda_rxt', -1) }} AS nr_seq_agenda_rxt,
    {{ fill_null_bigint('d.cd_prestador_solic_tiss', -1) }} AS cd_prestador_solic_tiss,
    {{ standardize_text_initcap('d.ds_prestador_solic_tiss', "'indefinido'") }} AS ds_prestador_solic_tiss,
    {{ normalize_decimal('d.vl_tx_desconto', 2, -1) }} AS vl_tx_desconto,
    {{ normalize_decimal('d.vl_tx_adm', 2, -1) }} AS vl_tx_adm,
    {{ fill_null_bigint('d.cd_medico_honor_tiss', -1) }} AS cd_medico_honor_tiss,
    {{ fill_null_bigint('d.nr_controle', -1) }} AS nr_controle,
    {{ fill_null_bigint('d.nr_seq_regra_taxa_cir', -1) }} AS nr_seq_regra_taxa_cir,
    {{ fill_null_bigint('d.nr_seq_proc_orig', -1) }} AS nr_seq_proc_orig,
    {{ fill_null_bigint('d.nr_sequencia_gas', -1) }} AS nr_sequencia_gas,
    {{ fill_null_bigint('d.nr_seq_etapa_checkup', -1) }} AS nr_seq_etapa_checkup,
    {{ fill_null_bigint('d.nr_seq_checkup_etapa', -1) }} AS nr_seq_checkup_etapa,
    {{ standardize_enum('d.ie_via_hemodinamica', "'i'") }} AS ie_via_hemodinamica,
    {{ fill_null_bigint('d.cd_regra_repasse', -1) }} AS cd_regra_repasse,
    {{ standardize_enum('d.ie_trat_conta_rn', "'i'") }} AS ie_trat_conta_rn,
    {{ fill_null_bigint('d.nr_seq_reg_proced', -1) }} AS nr_seq_reg_proced,
    {{ fill_null_bigint('d.nr_seq_pepo', -1) }} AS nr_seq_pepo,
    {{ fill_null_bigint('d.nr_seq_motivo_incl', -1) }} AS nr_seq_motivo_incl,
    {{ standardize_date('d.dh_conversao_manual') }} AS dt_conversao_manual,
    {{ standardize_documents('d.cd_cgc_prest_honor_tiss', 14) }} AS cd_cgc_prest_honor_tiss,
    {{ fill_null_bigint('d.nr_seq_transfusao', -1) }} AS nr_seq_transfusao,
    {{ fill_null_bigint('d.nr_seq_reserva', -1) }} AS nr_seq_reserva,
    {{ standardize_enum('d.ie_lado', "'i'") }} AS ie_lado,
    {{ fill_null_bigint('d.nr_seq_hc_equipamento', -1) }} AS nr_seq_hc_equipamento,
    {{ standardize_date('d.dh_vinc_proced_adic') }} AS dt_vinc_proced_adic,
    {{ standardize_text_initcap('d.ds_indicacao', "'indefinido'") }} AS ds_indicacao,
    {{ fill_null_bigint('d.cd_tipo_anestesia', -1) }} AS cd_tipo_anestesia,
    {{ fill_null_bigint('d.nr_seq_lanc_acao', -1) }} AS nr_seq_lanc_acao,
    {{ fill_null_bigint('d.nr_seq_material', -1) }} AS nr_seq_material,
    {{ standardize_enum('d.ie_carater_cirurgia', "'i'") }} AS ie_carater_cirurgia,
    {{ standardize_text_initcap('d.ds_just_valor_inf', "'indefinido'") }} AS ds_just_valor_inf,
    {{ fill_null_bigint('d.nr_fone_integracao', -1) }} AS nr_fone_integracao,
    {{ standardize_date('d.dh_ligacao_integracao') }} AS dt_ligacao_integracao,
    {{ standardize_text_initcap('d.ds_just_alter_data', "'indefinido'") }} AS ds_just_alter_data,
    {{ fill_null_bigint('d.cd_medico_prev_laudo', -1) }} AS cd_medico_prev_laudo,
    {{ fill_null_bigint('d.nr_seq_orig_audit', -1) }} AS nr_seq_orig_audit,
    {{ fill_null_bigint('d.nr_seq_servico', -1) }} AS nr_seq_servico,
    {{ fill_null_bigint('d.nr_seq_servico_classif', -1) }} AS nr_seq_servico_classif,
    {{ fill_null_bigint('d.nr_seq_sus_equipe', -1) }} AS nr_seq_sus_equipe,
    {{ fill_null_bigint('d.nr_seq_proc_ditado', -1) }} AS nr_seq_proc_ditado,
    {{ fill_null_bigint('d.nr_seq_crit_honorario', -1) }} AS nr_seq_crit_honorario,
    {{ standardize_enum('d.ie_tx_cir_tempo', "'i'") }} AS ie_tx_cir_tempo,
    {{ fill_null_bigint('d.nr_seq_pe_prescr', -1) }} AS nr_seq_pe_prescr,
    {{ fill_null_bigint('d.cd_medico_autenticacao', -1) }} AS cd_medico_autenticacao,
    {{ standardize_date('d.dh_autenticacao') }} AS dt_autenticacao,
    {{ standardize_text_initcap('d.ds_biometria', "'indefinido'") }} AS ds_biometria,
    {{ fill_null_bigint('d.nr_seq_prescr_mat', -1) }} AS nr_seq_prescr_mat,
    {{ fill_null_bigint('d.nr_seq_solucao', -1) }} AS nr_seq_solucao,
    {{ fill_null_bigint('d.nr_seq_proc_desdob', -1) }} AS nr_seq_proc_desdob,
    {{ fill_null_bigint('d.cd_medico_residente', -1) }} AS cd_medico_residente,
    {{ standardize_enum('d.ie_retorno', "'i'") }} AS ie_retorno,
    {{ fill_null_bigint('d.nr_ato_ipasgo', -1) }} AS nr_ato_ipasgo,
    {{ fill_null_bigint('d.nr_seq_conta_reversao', -1) }} AS nr_seq_conta_reversao,
    {{ fill_null_bigint('d.nr_seq_regra_pepo', -1) }} AS nr_seq_regra_pepo,
    {{ standardize_text_initcap('d.ds_proc_tuss', "'indefinido'") }} AS ds_proc_tuss,
    {{ fill_null_bigint('d.nr_seq_tuss_item', -1) }} AS nr_seq_tuss_item,
    {{ fill_null_bigint('d.cd_sequencia_parametro', -1) }} AS cd_sequencia_parametro,
    {{ normalize_decimal('d.tx_auxiliar', 2, -1) }} AS tx_auxiliar,
    {{ fill_null_bigint('d.cd_autorizacao_prest', -1) }} AS cd_autorizacao_prest,
    {{ fill_null_bigint('d.nr_presc_mipres', -1) }} AS nr_presc_mipres,
    {{ fill_null_bigint('d.cd_id_entrega', -1) }} AS cd_id_entrega,
    {{ fill_null_bigint('d.nr_seq_proc_pacote_origem', -1) }} AS nr_seq_proc_pacote_origem
    {{ silver_audit_columns() }}
  FROM latest_by_pk d
)
, final AS (
  SELECT *
  FROM shaped
  WHERE NOT _is_deleted
)
SELECT * FROM final
