{#- Silver: one column per line + macros (dbt/macros/). PK: nr_atendimento. -#}
{{
  config(
    materialized='incremental',
    schema='silver',
    unique_key='nr_atendimento',
    incremental_strategy='merge',
    merge_update_columns=[
      'cd_pessoa_fisica', 'cd_estabelecimento', 'cd_procedencia', 'dt_entrada',
      'ie_tipo_atendimento', 'dt_atualizacao', 'nm_usuario', 'cd_medico_resp', 'cd_motivo_alta',
      'ds_sintoma_paciente', 'ds_observacao', 'dt_alta', 'ie_clinica', 'nm_usuario_atend',
      'ie_responsavel', 'dt_fim_conta', 'ie_fim_conta', 'nr_cat', 'ds_causa_externa',
      'cd_cgc_seguradora', 'nr_bilhete', 'nr_serie_bilhete', 'ie_carater_inter_sus',
      'ie_vinculo_sus', 'ie_tipo_convenio', 'ie_tipo_atend_bpa', 'ie_grupo_atend_bpa',
      'cd_medico_atendimento', 'dt_alta_interno', 'nr_seq_unid_atual', 'nr_seq_unid_int',
      'nr_atend_original', 'qt_dia_longa_perm', 'dt_inicio_atendimento', 'ie_permite_visita',
      'ie_status_atendimento', 'dt_previsto_alta', 'nm_usuario_alta', 'cd_pessoa_responsavel',
      'dt_atend_medico', 'dt_fim_consulta', 'dt_medicacao', 'dt_saida_real', 'ie_clinica_alta',
      'dt_lib_medico', 'nr_seq_regra_funcao', 'nr_seq_local_pa', 'nr_seq_tipo_acidente',
      'dt_ocorrencia', 'ds_pend_autorizacao', 'nr_seq_check_list', 'dt_fim_triagem',
      'nr_reserva_leito', 'ie_paciente_isolado', 'ie_permite_visita_rel', 'ds_senha',
      'ie_probabilidade_alta', 'nr_seq_forma_chegada', 'nr_seq_indicacao', 'ds_obs_alta',
      'cd_pessoa_indic', 'nm_medico_externo', 'nr_gestante_pre_natal', 'nr_seq_forma_laudo',
      'dt_alta_medico', 'cd_motivo_alta_medica', 'nr_seq_pq_protocolo', 'ie_extra_teto',
      'cd_psicologo', 'nr_seq_classificacao', 'ds_senha_qmatic', 'nr_seq_queixa', 'nr_seq_triagem',
      'cd_medico_referido', 'ie_necropsia', 'nr_seq_classif_medico', 'ie_tipo_consulta',
      'ie_tipo_saida_consulta', 'ie_tipo_atend_tiss', 'dt_impressao', 'cd_pessoa_juridica_indic',
      'nr_atendimento_mae', 'ie_trat_conta_rn', 'qt_dias_prev_inter', 'nr_seq_grau_parentesco',
      'ie_boletim_inform', 'dt_chamada_paciente', 'ie_chamado', 'ds_obs_prev_alta',
      'ie_avisar_medico_referido', 'cd_medico_chamado', 'nr_atend_alta', 'dt_saida_prev_loc_pa',
      'ie_status_pa', 'dt_liberacao_enfermagem', 'dt_reavaliacao_medica', 'ds_justif_saida_real',
      'nm_usuario_triagem', 'nr_seq_ficha', 'dt_recebimento_senha', 'ie_prm', 'dt_ver_prev_alta',
      'nr_seq_cat', 'dt_atend_original', 'dt_chamada_enfermagem', 'nr_seq_local_destino',
      'ie_divulgar_obito', 'nr_seq_topografia', 'nr_seq_tipo_lesao', 'ie_clinica_ant',
      'cd_perfil_ativo', 'nm_usuario_intern', 'ds_obs_alta_medic', 'ie_modo_internacao',
      'cd_municipio_ocorrencia', 'dt_usuario_intern', 'dt_chamada_reavaliacao',
      'dt_inicio_reavaliacao', 'nr_vinculo_censo', 'dt_chegada_paciente', 'ds_vinculo_censo',
      'nr_seq_triagem_prioridade', 'nm_usuario_saida', 'nr_seq_triagem_old', 'crm_medico_externo',
      'dt_fim_reavaliacao', 'cd_setor_obito', 'nm_usuario_alta_medica', 'nr_seq_segurado',
      'dt_alta_tesouraria', 'nr_atend_origem_pa', 'cd_cgc_indicacao', 'dt_inicio_observacao',
      'dt_fim_observacao', 'nr_seq_pac_senha_fila', 'dt_cancelamento', 'nm_usuario_cancelamento',
      'nm_usuario_prob_alta', 'ie_permite_acomp', 'nr_seq_informacao', 'ds_informacao',
      'nr_seq_tipo_midia', 'nm_inicio_atendimento', 'nm_fim_triagem', 'nr_dias_prev_alta',
      'ie_declaracao_obito', 'dt_chamada_medic', 'dt_chegada_medic', 'nr_seq_atend_pls',
      'nr_seq_evento_atend', 'dt_descolonizar_paciente', 'nm_descolonizar_paciente',
      'dt_checagem_adep', 'ie_laudo_preenchido', 'dt_impressao_alta', 'nr_seq_classif_esp',
      'cd_medico_preferencia', 'ds_obs_prior', 'vl_consulta', 'ds_obs_pa', 'nr_conv_interno',
      'dt_inicio_prescr_pa', 'dt_fim_prescr_pa', 'dt_inicio_esp_exame', 'dt_fim_esp_exame',
      'nr_seq_pa_status', 'nr_seq_registro', 'ie_assinou_termo_biobanco', 'ds_observacao_biobanco',
      'nr_seq_motivo_biobanco', 'nm_usuario_biobanco', 'dt_atualizacao_biobanco',
      'dt_liberacao_financeiro', 'nr_seq_ficha_lote', 'ie_tipo_endereco_entrega',
      'cd_setor_usuario_atend', 'dt_ultima_menstruacao', 'qt_ig_semana', 'qt_ig_dia',
      'cd_funcao_alta_medica', 'nr_submotivo_alta', 'ie_tipo_status_alta', 'ie_tipo_alta',
      'ie_tipo_vaga', 'cd_setor_desejado', 'cd_tipo_acomod_desej', 'nr_int_cross',
      'dt_classif_risco', 'nr_seq_ficha_lote_ant', 'ie_classif_lote_ent', 'cd_medico_infect',
      'nr_seq_tipo_obs_alta', 'nr_atend_origem_bpa', 'ie_liberado_checkout', 'nr_seq_oftalmo',
      'ds_senha_internet', 'dt_atualizacao_nrec', 'nm_usuario_nrec', 'ie_paciente_gravida',
      'ds_utc', 'ie_horario_verao', 'ie_nivel_atencao', 'ds_utc_atualizacao', 'nr_seq_episodio',
      'cd_lugar_acc', 'ie_tipo_serv_mx', 'cd_serv_entrada_mx', 'cd_serv_sec_mx', 'cd_serv_ter_mx',
      'cd_serv_alta_mx', 'nr_seq_tipo_admissao_fat', 'ie_inform_incompletas',
      'btn_alterar_dados_resp', 'ie_tipo_complemento_resp', '_is_deleted', '_cdc_op',
      '_cdc_event_at', '_cdc_ts_ms', '_bronze_row_hash', '_bronze_loaded_at', '_dbt_invocation_id',
    ],
    file_format='iceberg',
    on_schema_change='append_new_columns',
    tags=["silver", "tasy", "atendimento_paciente"],
    post_hook=post_hook_delete_source_tombstones('bronze_tasy_atendimento_paciente', 'nr_atendimento', '_is_deleted')
  )
}}

WITH base AS (
  SELECT * FROM {{ ref('bronze_tasy_atendimento_paciente') }} b
  {% if is_incremental() %}
  WHERE b._bronze_loaded_at > (
      SELECT COALESCE(MAX(s._silver_processed_at), CAST('1900-01-01' AS TIMESTAMP))
      FROM {{ this }} s
  )
  {% endif %}
)
, latest_by_pk AS (
  SELECT *
  FROM (
    SELECT
        b.*
      , ROW_NUMBER() OVER (
          PARTITION BY b.nr_atendimento
          ORDER BY
              CAST(COALESCE(b._cdc_ts_ms, 0) AS BIGINT) DESC
            , CAST(COALESCE(b.__source_txid, 0) AS BIGINT) DESC
        ) AS _rn
    FROM base b
  ) x
  WHERE _rn = 1
)
,
shaped AS (
  SELECT
    d.nr_atendimento AS nr_atendimento,
    {{ fill_null_bigint('d.cd_pessoa_fisica', -1) }} AS cd_pessoa_fisica,
    {{ fill_null_bigint('d.cd_estabelecimento', -1) }} AS cd_estabelecimento,
    {{ fill_null_bigint('d.cd_procedencia', -1) }} AS cd_procedencia,
    {{ standardize_date('d.dh_entrada') }} AS dt_entrada,
    {{ standardize_enum('d.ie_tipo_atendimento', "'i'") }} AS ie_tipo_atendimento,
    {{ standardize_date('d.dh_atualizacao') }} AS dt_atualizacao,
    {{ standardize_text_initcap('d.nm_usuario', "'indefinido'") }} AS nm_usuario,
    {{ fill_null_bigint('d.cd_medico_resp', -1) }} AS cd_medico_resp,
    {{ fill_null_bigint('d.cd_motivo_alta', -1) }} AS cd_motivo_alta,
    {{ standardize_text_initcap('d.ds_sintoma_paciente', "'indefinido'") }} AS ds_sintoma_paciente,
    {{ standardize_text_initcap('d.ds_observacao', "'indefinido'") }} AS ds_observacao,
    {{ standardize_date('d.dh_alta') }} AS dt_alta,
    {{ standardize_enum('d.ie_clinica', "'i'") }} AS ie_clinica,
    {{ standardize_text_initcap('d.nm_usuario_atend', "'indefinido'") }} AS nm_usuario_atend,
    {{ standardize_enum('d.ie_responsavel', "'i'") }} AS ie_responsavel,
    {{ standardize_date('d.dh_fim_conta') }} AS dt_fim_conta,
    {{ standardize_enum('d.ie_fim_conta', "'i'") }} AS ie_fim_conta,
    {{ fill_null_bigint('d.nr_cat', -1) }} AS nr_cat,
    {{ standardize_text_initcap('d.ds_causa_externa', "'indefinido'") }} AS ds_causa_externa,
    {{ standardize_documents('d.cd_cgc_seguradora', 14) }} AS cd_cgc_seguradora,
    {{ fill_null_bigint('d.nr_bilhete', -1) }} AS nr_bilhete,
    {{ fill_null_bigint('d.nr_serie_bilhete', -1) }} AS nr_serie_bilhete,
    {{ standardize_enum('d.ie_carater_inter_sus', "'i'") }} AS ie_carater_inter_sus,
    {{ standardize_enum('d.ie_vinculo_sus', "'i'") }} AS ie_vinculo_sus,
    {{ standardize_enum('d.ie_tipo_convenio', "'i'") }} AS ie_tipo_convenio,
    {{ standardize_enum('d.ie_tipo_atend_bpa', "'i'") }} AS ie_tipo_atend_bpa,
    {{ standardize_enum('d.ie_grupo_atend_bpa', "'i'") }} AS ie_grupo_atend_bpa,
    {{ fill_null_bigint('d.cd_medico_atendimento', -1) }} AS cd_medico_atendimento,
    {{ standardize_date('d.dh_alta_interno') }} AS dt_alta_interno,
    {{ fill_null_bigint('d.nr_seq_unid_atual', -1) }} AS nr_seq_unid_atual,
    {{ fill_null_bigint('d.nr_seq_unid_int', -1) }} AS nr_seq_unid_int,
    {{ fill_null_bigint('d.nr_atend_original', -1) }} AS nr_atend_original,
    {{ normalize_decimal('d.qt_dia_longa_perm', 2, -1) }} AS qt_dia_longa_perm,
    {{ standardize_date('d.dh_inicio_atendimento') }} AS dt_inicio_atendimento,
    {{ standardize_enum('d.ie_permite_visita', "'i'") }} AS ie_permite_visita,
    {{ standardize_enum('d.ie_status_atendimento', "'i'") }} AS ie_status_atendimento,
    {{ standardize_date('d.dh_previsto_alta') }} AS dt_previsto_alta,
    {{ standardize_text_initcap('d.nm_usuario_alta', "'indefinido'") }} AS nm_usuario_alta,
    {{ fill_null_bigint('d.cd_pessoa_responsavel', -1) }} AS cd_pessoa_responsavel,
    {{ standardize_date('d.dh_atend_medico') }} AS dt_atend_medico,
    {{ standardize_date('d.dh_fim_consulta') }} AS dt_fim_consulta,
    {{ standardize_date('d.dh_medicacao') }} AS dt_medicacao,
    {{ standardize_date('d.dh_saida_real') }} AS dt_saida_real,
    {{ standardize_enum('d.ie_clinica_alta', "'i'") }} AS ie_clinica_alta,
    {{ standardize_date('d.dh_lib_medico') }} AS dt_lib_medico,
    {{ fill_null_bigint('d.nr_seq_regra_funcao', -1) }} AS nr_seq_regra_funcao,
    {{ fill_null_bigint('d.nr_seq_local_pa', -1) }} AS nr_seq_local_pa,
    {{ fill_null_bigint('d.nr_seq_tipo_acidente', -1) }} AS nr_seq_tipo_acidente,
    {{ standardize_date('d.dh_ocorrencia') }} AS dt_ocorrencia,
    {{ standardize_text_initcap('d.ds_pend_autorizacao', "'indefinido'") }} AS ds_pend_autorizacao,
    {{ fill_null_bigint('d.nr_seq_check_list', -1) }} AS nr_seq_check_list,
    {{ standardize_date('d.dh_fim_triagem') }} AS dt_fim_triagem,
    {{ fill_null_bigint('d.nr_reserva_leito', -1) }} AS nr_reserva_leito,
    {{ standardize_enum('d.ie_paciente_isolado', "'i'") }} AS ie_paciente_isolado,
    {{ standardize_enum('d.ie_permite_visita_rel', "'i'") }} AS ie_permite_visita_rel,
    {{ standardize_text_initcap('d.ds_senha', "'indefinido'") }} AS ds_senha,
    {{ standardize_enum('d.ie_probabilidade_alta', "'i'") }} AS ie_probabilidade_alta,
    {{ fill_null_bigint('d.nr_seq_forma_chegada', -1) }} AS nr_seq_forma_chegada,
    {{ fill_null_bigint('d.nr_seq_indicacao', -1) }} AS nr_seq_indicacao,
    {{ standardize_text_initcap('d.ds_obs_alta', "'indefinido'") }} AS ds_obs_alta,
    {{ fill_null_bigint('d.cd_pessoa_indic', -1) }} AS cd_pessoa_indic,
    {{ standardize_text_initcap('d.nm_medico_externo', "'indefinido'") }} AS nm_medico_externo,
    {{ fill_null_bigint('d.nr_gestante_pre_natal', -1) }} AS nr_gestante_pre_natal,
    {{ fill_null_bigint('d.nr_seq_forma_laudo', -1) }} AS nr_seq_forma_laudo,
    {{ standardize_date('d.dh_alta_medico') }} AS dt_alta_medico,
    {{ fill_null_bigint('d.cd_motivo_alta_medica', -1) }} AS cd_motivo_alta_medica,
    {{ fill_null_bigint('d.nr_seq_pq_protocolo', -1) }} AS nr_seq_pq_protocolo,
    {{ standardize_enum('d.ie_extra_teto', "'i'") }} AS ie_extra_teto,
    {{ fill_null_bigint('d.cd_psicologo', -1) }} AS cd_psicologo,
    {{ fill_null_bigint('d.nr_seq_classificacao', -1) }} AS nr_seq_classificacao,
    {{ standardize_text_initcap('d.ds_senha_qmatic', "'indefinido'") }} AS ds_senha_qmatic,
    {{ fill_null_bigint('d.nr_seq_queixa', -1) }} AS nr_seq_queixa,
    {{ fill_null_bigint('d.nr_seq_triagem', -1) }} AS nr_seq_triagem,
    {{ fill_null_bigint('d.cd_medico_referido', -1) }} AS cd_medico_referido,
    {{ standardize_enum('d.ie_necropsia', "'i'") }} AS ie_necropsia,
    {{ fill_null_bigint('d.nr_seq_classif_medico', -1) }} AS nr_seq_classif_medico,
    {{ standardize_enum('d.ie_tipo_consulta', "'i'") }} AS ie_tipo_consulta,
    {{ standardize_enum('d.ie_tipo_saida_consulta', "'i'") }} AS ie_tipo_saida_consulta,
    {{ standardize_enum('d.ie_tipo_atend_tiss', "'i'") }} AS ie_tipo_atend_tiss,
    {{ standardize_date('d.dh_impressao') }} AS dt_impressao,
    {{ fill_null_bigint('d.cd_pessoa_juridica_indic', -1) }} AS cd_pessoa_juridica_indic,
    {{ fill_null_bigint('d.nr_atendimento_mae', -1) }} AS nr_atendimento_mae,
    {{ standardize_enum('d.ie_trat_conta_rn', "'i'") }} AS ie_trat_conta_rn,
    {{ normalize_decimal('d.qt_dias_prev_inter', 2, -1) }} AS qt_dias_prev_inter,
    {{ fill_null_bigint('d.nr_seq_grau_parentesco', -1) }} AS nr_seq_grau_parentesco,
    {{ standardize_enum('d.ie_boletim_inform', "'i'") }} AS ie_boletim_inform,
    {{ standardize_date('d.dh_chamada_paciente') }} AS dt_chamada_paciente,
    {{ standardize_enum('d.ie_chamado', "'i'") }} AS ie_chamado,
    {{ standardize_text_initcap('d.ds_obs_prev_alta', "'indefinido'") }} AS ds_obs_prev_alta,
    {{ standardize_enum('d.ie_avisar_medico_referido', "'i'") }} AS ie_avisar_medico_referido,
    {{ fill_null_bigint('d.cd_medico_chamado', -1) }} AS cd_medico_chamado,
    {{ fill_null_bigint('d.nr_atend_alta', -1) }} AS nr_atend_alta,
    {{ standardize_date('d.dh_saida_prev_loc_pa') }} AS dt_saida_prev_loc_pa,
    {{ standardize_enum('d.ie_status_pa', "'i'") }} AS ie_status_pa,
    {{ standardize_date('d.dh_liberacao_enfermagem') }} AS dt_liberacao_enfermagem,
    {{ standardize_date('d.dh_reavaliacao_medica') }} AS dt_reavaliacao_medica,
    {{ standardize_text_initcap('d.ds_justif_saida_real', "'indefinido'") }} AS ds_justif_saida_real,
    {{ standardize_text_initcap('d.nm_usuario_triagem', "'indefinido'") }} AS nm_usuario_triagem,
    {{ fill_null_bigint('d.nr_seq_ficha', -1) }} AS nr_seq_ficha,
    {{ standardize_date('d.dh_recebimento_senha') }} AS dt_recebimento_senha,
    {{ standardize_enum('d.ie_prm', "'i'") }} AS ie_prm,
    {{ standardize_date('d.dh_ver_prev_alta') }} AS dt_ver_prev_alta,
    {{ fill_null_bigint('d.nr_seq_cat', -1) }} AS nr_seq_cat,
    {{ standardize_date('d.dh_atend_original') }} AS dt_atend_original,
    {{ standardize_date('d.dh_chamada_enfermagem') }} AS dt_chamada_enfermagem,
    {{ fill_null_bigint('d.nr_seq_local_destino', -1) }} AS nr_seq_local_destino,
    {{ standardize_enum('d.ie_divulgar_obito', "'i'") }} AS ie_divulgar_obito,
    {{ fill_null_bigint('d.nr_seq_topografia', -1) }} AS nr_seq_topografia,
    {{ fill_null_bigint('d.nr_seq_tipo_lesao', -1) }} AS nr_seq_tipo_lesao,
    {{ standardize_enum('d.ie_clinica_ant', "'i'") }} AS ie_clinica_ant,
    {{ fill_null_bigint('d.cd_perfil_ativo', -1) }} AS cd_perfil_ativo,
    {{ standardize_text_initcap('d.nm_usuario_intern', "'indefinido'") }} AS nm_usuario_intern,
    {{ standardize_text_initcap('d.ds_obs_alta_medic', "'indefinido'") }} AS ds_obs_alta_medic,
    {{ standardize_enum('d.ie_modo_internacao', "'i'") }} AS ie_modo_internacao,
    {{ fill_null_bigint('d.cd_municipio_ocorrencia', -1) }} AS cd_municipio_ocorrencia,
    {{ standardize_date('d.dh_usuario_intern') }} AS dt_usuario_intern,
    {{ standardize_date('d.dh_chamada_reavaliacao') }} AS dt_chamada_reavaliacao,
    {{ standardize_date('d.dh_inicio_reavaliacao') }} AS dt_inicio_reavaliacao,
    {{ fill_null_bigint('d.nr_vinculo_censo', -1) }} AS nr_vinculo_censo,
    {{ standardize_date('d.dh_chegada_paciente') }} AS dt_chegada_paciente,
    {{ standardize_text_initcap('d.ds_vinculo_censo', "'indefinido'") }} AS ds_vinculo_censo,
    {{ fill_null_bigint('d.nr_seq_triagem_prioridade', -1) }} AS nr_seq_triagem_prioridade,
    {{ standardize_text_initcap('d.nm_usuario_saida', "'indefinido'") }} AS nm_usuario_saida,
    {{ fill_null_bigint('d.nr_seq_triagem_old', -1) }} AS nr_seq_triagem_old,
    {{ standardize_text_initcap('d.crm_medico_externo', "'indefinido'") }} AS crm_medico_externo,
    {{ standardize_date('d.dh_fim_reavaliacao') }} AS dt_fim_reavaliacao,
    {{ fill_null_bigint('d.cd_setor_obito', -1) }} AS cd_setor_obito,
    {{ standardize_text_initcap('d.nm_usuario_alta_medica', "'indefinido'") }} AS nm_usuario_alta_medica,
    {{ fill_null_bigint('d.nr_seq_segurado', -1) }} AS nr_seq_segurado,
    {{ standardize_date('d.dh_alta_tesouraria') }} AS dt_alta_tesouraria,
    {{ fill_null_bigint('d.nr_atend_origem_pa', -1) }} AS nr_atend_origem_pa,
    {{ standardize_documents('d.cd_cgc_indicacao', 14) }} AS cd_cgc_indicacao,
    {{ standardize_date('d.dh_inicio_observacao') }} AS dt_inicio_observacao,
    {{ standardize_date('d.dh_fim_observacao') }} AS dt_fim_observacao,
    {{ fill_null_bigint('d.nr_seq_pac_senha_fila', -1) }} AS nr_seq_pac_senha_fila,
    {{ standardize_date('d.dh_cancelamento') }} AS dt_cancelamento,
    {{ standardize_text_initcap('d.nm_usuario_cancelamento', "'indefinido'") }} AS nm_usuario_cancelamento,
    {{ standardize_text_initcap('d.nm_usuario_prob_alta', "'indefinido'") }} AS nm_usuario_prob_alta,
    {{ standardize_enum('d.ie_permite_acomp', "'i'") }} AS ie_permite_acomp,
    {{ fill_null_bigint('d.nr_seq_informacao', -1) }} AS nr_seq_informacao,
    {{ standardize_text_initcap('d.ds_informacao', "'indefinido'") }} AS ds_informacao,
    {{ fill_null_bigint('d.nr_seq_tipo_midia', -1) }} AS nr_seq_tipo_midia,
    {{ standardize_text_initcap('d.nm_inicio_atendimento', "'indefinido'") }} AS nm_inicio_atendimento,
    {{ standardize_text_initcap('d.nm_fim_triagem', "'indefinido'") }} AS nm_fim_triagem,
    {{ fill_null_bigint('d.nr_dias_prev_alta', -1) }} AS nr_dias_prev_alta,
    {{ standardize_enum('d.ie_declaracao_obito', "'i'") }} AS ie_declaracao_obito,
    {{ standardize_date('d.dh_chamada_medic') }} AS dt_chamada_medic,
    {{ standardize_date('d.dh_chegada_medic') }} AS dt_chegada_medic,
    {{ fill_null_bigint('d.nr_seq_atend_pls', -1) }} AS nr_seq_atend_pls,
    {{ fill_null_bigint('d.nr_seq_evento_atend', -1) }} AS nr_seq_evento_atend,
    {{ standardize_date('d.dh_descolonizar_paciente') }} AS dt_descolonizar_paciente,
    {{ standardize_text_initcap('d.nm_descolonizar_paciente', "'indefinido'") }} AS nm_descolonizar_paciente,
    {{ standardize_date('d.dh_checagem_adep') }} AS dt_checagem_adep,
    {{ standardize_enum('d.ie_laudo_preenchido', "'i'") }} AS ie_laudo_preenchido,
    {{ standardize_date('d.dh_impressao_alta') }} AS dt_impressao_alta,
    {{ fill_null_bigint('d.nr_seq_classif_esp', -1) }} AS nr_seq_classif_esp,
    {{ fill_null_bigint('d.cd_medico_preferencia', -1) }} AS cd_medico_preferencia,
    {{ standardize_text_initcap('d.ds_obs_prior', "'indefinido'") }} AS ds_obs_prior,
    {{ normalize_decimal('d.vl_consulta', 2, -1) }} AS vl_consulta,
    {{ standardize_text_initcap('d.ds_obs_pa', "'indefinido'") }} AS ds_obs_pa,
    {{ fill_null_bigint('d.nr_conv_interno', -1) }} AS nr_conv_interno,
    {{ standardize_date('d.dh_inicio_prescr_pa') }} AS dt_inicio_prescr_pa,
    {{ standardize_date('d.dh_fim_prescr_pa') }} AS dt_fim_prescr_pa,
    {{ standardize_date('d.dh_inicio_esp_exame') }} AS dt_inicio_esp_exame,
    {{ standardize_date('d.dh_fim_esp_exame') }} AS dt_fim_esp_exame,
    {{ fill_null_bigint('d.nr_seq_pa_status', -1) }} AS nr_seq_pa_status,
    {{ fill_null_bigint('d.nr_seq_registro', -1) }} AS nr_seq_registro,
    {{ standardize_enum('d.ie_assinou_termo_biobanco', "'i'") }} AS ie_assinou_termo_biobanco,
    {{ standardize_text_initcap('d.ds_observacao_biobanco', "'indefinido'") }} AS ds_observacao_biobanco,
    {{ fill_null_bigint('d.nr_seq_motivo_biobanco', -1) }} AS nr_seq_motivo_biobanco,
    {{ standardize_text_initcap('d.nm_usuario_biobanco', "'indefinido'") }} AS nm_usuario_biobanco,
    {{ standardize_date('d.dh_atualizacao_biobanco') }} AS dt_atualizacao_biobanco,
    {{ standardize_date('d.dh_liberacao_financeiro') }} AS dt_liberacao_financeiro,
    {{ fill_null_bigint('d.nr_seq_ficha_lote', -1) }} AS nr_seq_ficha_lote,
    {{ standardize_enum('d.ie_tipo_endereco_entrega', "'i'") }} AS ie_tipo_endereco_entrega,
    {{ fill_null_bigint('d.cd_setor_usuario_atend', -1) }} AS cd_setor_usuario_atend,
    {{ standardize_date('d.dh_ultima_menstruacao') }} AS dt_ultima_menstruacao,
    {{ normalize_decimal('d.qt_ig_semana', 2, -1) }} AS qt_ig_semana,
    {{ normalize_decimal('d.qt_ig_dia', 2, -1) }} AS qt_ig_dia,
    {{ fill_null_bigint('d.cd_funcao_alta_medica', -1) }} AS cd_funcao_alta_medica,
    {{ fill_null_bigint('d.nr_submotivo_alta', -1) }} AS nr_submotivo_alta,
    {{ standardize_enum('d.ie_tipo_status_alta', "'i'") }} AS ie_tipo_status_alta,
    {{ standardize_enum('d.ie_tipo_alta', "'i'") }} AS ie_tipo_alta,
    {{ standardize_enum('d.ie_tipo_vaga', "'i'") }} AS ie_tipo_vaga,
    {{ fill_null_bigint('d.cd_setor_desejado', -1) }} AS cd_setor_desejado,
    {{ fill_null_bigint('d.cd_tipo_acomod_desej', -1) }} AS cd_tipo_acomod_desej,
    {{ fill_null_bigint('d.nr_int_cross', -1) }} AS nr_int_cross,
    {{ standardize_date('d.dh_classif_risco') }} AS dt_classif_risco,
    {{ fill_null_bigint('d.nr_seq_ficha_lote_ant', -1) }} AS nr_seq_ficha_lote_ant,
    {{ standardize_enum('d.ie_classif_lote_ent', "'i'") }} AS ie_classif_lote_ent,
    {{ fill_null_bigint('d.cd_medico_infect', -1) }} AS cd_medico_infect,
    {{ fill_null_bigint('d.nr_seq_tipo_obs_alta', -1) }} AS nr_seq_tipo_obs_alta,
    {{ fill_null_bigint('d.nr_atend_origem_bpa', -1) }} AS nr_atend_origem_bpa,
    {{ standardize_enum('d.ie_liberado_checkout', "'i'") }} AS ie_liberado_checkout,
    {{ fill_null_bigint('d.nr_seq_oftalmo', -1) }} AS nr_seq_oftalmo,
    {{ standardize_text_initcap('d.ds_senha_internet', "'indefinido'") }} AS ds_senha_internet,
    {{ standardize_date('d.dh_atualizacao_nrec') }} AS dt_atualizacao_nrec,
    {{ standardize_text_initcap('d.nm_usuario_nrec', "'indefinido'") }} AS nm_usuario_nrec,
    {{ standardize_enum('d.ie_paciente_gravida', "'i'") }} AS ie_paciente_gravida,
    {{ standardize_text_initcap('d.ds_utc', "'indefinido'") }} AS ds_utc,
    {{ standardize_enum('d.ie_horario_verao', "'i'") }} AS ie_horario_verao,
    {{ standardize_enum('d.ie_nivel_atencao', "'i'") }} AS ie_nivel_atencao,
    {{ standardize_text_initcap('d.ds_utc_atualizacao', "'indefinido'") }} AS ds_utc_atualizacao,
    {{ fill_null_bigint('d.nr_seq_episodio', -1) }} AS nr_seq_episodio,
    {{ fill_null_bigint('d.cd_lugar_acc', -1) }} AS cd_lugar_acc,
    {{ standardize_enum('d.ie_tipo_serv_mx', "'i'") }} AS ie_tipo_serv_mx,
    {{ fill_null_bigint('d.cd_serv_entrada_mx', -1) }} AS cd_serv_entrada_mx,
    {{ fill_null_bigint('d.cd_serv_sec_mx', -1) }} AS cd_serv_sec_mx,
    {{ fill_null_bigint('d.cd_serv_ter_mx', -1) }} AS cd_serv_ter_mx,
    {{ fill_null_bigint('d.cd_serv_alta_mx', -1) }} AS cd_serv_alta_mx,
    {{ fill_null_bigint('d.nr_seq_tipo_admissao_fat', -1) }} AS nr_seq_tipo_admissao_fat,
    {{ standardize_enum('d.ie_inform_incompletas', "'i'") }} AS ie_inform_incompletas,
    {{ standardize_text_initcap('d.btn_alterar_dados_resp', "'indefinido'") }} AS btn_alterar_dados_resp,
    {{ standardize_enum('d.ie_tipo_complemento_resp', "'i'") }} AS ie_tipo_complemento_resp
    {{ silver_audit_columns() }}
  FROM latest_by_pk d
)
, final AS (
  SELECT *
  FROM shaped
  WHERE NOT _is_deleted
)
SELECT * FROM final
